# Generated by Django 3.1.7 on 2021-03-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(unique=True)),
                ('caption', models.CharField(max_length=2200)),
                ('pub_date', models.DateField()),
                ('likes_amount', models.IntegerField()),
                ('comments_amount', models.IntegerField()),
                ('views_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('instagram_id', models.PositiveIntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('local_path', models.CharField(max_length=500)),
                ('is_video', models.BooleanField(default=False)),
                ('instagram_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_from_instagram.instagrampost')),
                ('instagram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_from_instagram.instagramuser')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_from_instagram.instagramuser'),
        ),
    ]
